#@formatter:off
spring:
  jpa:
    generate-ddl: false
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/board?useUnicode=true&charaterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
server:
  port: 8081
